name: Daily LinkedIn Post

on:
  schedule:
    - cron: '30 12 * * *'  # Runs every day at 7:30 AM EST
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install openai

    - name: Run script
      env:
        OPENAI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      run: |
        echo "Creating used_prompts.json if missing..."
        touch used_prompts.json
        python daily_post.py
